ServerEvents.tags("item", event => {

    event.add("custom:reset_item", [
        "quark:seed_pouch",
        "minecraft:enchanted_book"
    ])

    event.add("custom:reset_tag", [
        "#minecraft:music_discs",
        "#forge:tools",
        "#forge:armors",
        "#forge:ingots",
        "#forge:nuggets",
        "#forge:gems",
        "#quark:vertical_slabs",
        "#quark:hollow_logs",
        "#quark:posts",
        "#aether:accessories",
        "#forge:dusts"
    ])

    event.add("custom:reset", [
        "@additionallanterns",
        "@chipped",
        "@comforts",
        "@constructionwand",
        "@cookingforblockheads",
        "@delightful",
        "@farmersdelight",
        "@ends_delight",
        "@nethersdelight",
        "@endersdelight",
        "@handcrafted",
        "@ironfurnaces",
        "@redstone_arsenal",
        "@darkutils",
        "@sophisticatedbackpacks",
        "@sophisticatedstorage",
        "@supplementaries",
        "@tinyredstone",
        "@mekanism",
        "@computercraft",
        "@functionalstorage",
        "@sfm",
        "@bhc",
        "@utilitix",
        "@utilitarian",
        "@industrialforegoing",
        "@ae2",
        "@ars_nouveau",
        "@create", // might be more specific later
        "@design_decor", // might be more specific later
        "@create_confectionery",
        "@railways",
        "@createcasing",
        "@createaddition",
        "@createdieselgenerators",
        "@createoreexcavation",
        "@copycats",
        "@refinedstorage",
        "@mob_grinding_utils",
        "@apotheosis",
        "@draconicevolution",
        "@architects_palette", // might be more specific later
        "@enderchests",
        "@endertanks",
        "@enderio",
        "@thermal_extra",
        "@thermal",
        "@exchangers",
        "@naturalist",
        "@reliquary",
        "@powah",
        "@rftoolsutility",
        "@rftoolscontrol",
        "@rftoolsstorage",
        "@rftoolsbase",
        "@rftoolspower",
        "@rftoolsbuilder",
        "@pedestals",
        "@dankstorage",
        "@itemcollectors",
        "@itemfilters",
        "@morered",
        "@botania",
        "@securitycraft",
        "@allthecompressed",
        "@alltheores",
        "@xnet",
        "@wsteaks",
        "@waystones",
        "@tetra",
        "@theurgy",
        "@structurize",
        "@silentgear",
        "@railcraft",
        "@productivebees",
        "@productivetrees",
        "@pneumaticcraft",
        "@moremekanismprocessing",
        "@mysticalagriculture",
        "@mahoutsukai",
        "@irons_spellbooks",
        "@ironjetpacks",
        "@gtceu",
        "@mythicbotany",
        "@xtonesreworked",

        "#custom:reset_item",
        "#custom:reset_tag",
    ])
})